### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by emchristiansen** [ViktorQvarfordt/vscode-pitch-black-theme#10]
I'd like to use this theme for my work coding, but I'm not allowed to unless it has an explicit license.
Please choose one 😁

If you don't care, MIT is a good default.

Thanks!

**Comment by ViktorQvarfordt** [comment]
Done :) https://github.com/ViktorQvarfordt/vscode-pitch-black-theme/blob/master/LICENSE
