### ISSUE TITLE
Please add a screenshot.png to help people discover this theme

### ISSUE THREAD

**Issue by emchristiansen** [ViktorQvarfordt/vscode-pitch-black-theme#11]
Please add a screenshot to help with discovery.
For example, see the Dracula theme:
https://github.com/dracula/visual-studio-code

I really like this theme and I think my coworkers would, too, but without a sample it's unlikely to be discovered by people browsing our internal VS Code extensions repo.

**Comment by ViktorQvarfordt** [comment]
Hi! Great idea. Would you like to open a PR where you add this to the Readme file?

**Comment by ViktorQvarfordt** [comment]
Closed by PR #12.
