### ISSUE TITLE
selection color is blinding

### ISSUE THREAD

**Issue by sharunkumar** [ViktorQvarfordt/vscode-pitch-black-theme#4]
when I select text in this theme, it is too light

![image](https://user-images.githubusercontent.com/715417/83971405-cba27980-a8f8-11ea-8a8c-45c1b05b64c9.png)

**Comment by mruf** [comment]
@sharunkumar 
As a workaround you can add this to your settings.json to override the theme's selection color:

`  "workbench.colorCustomizations": {
    "[Pitch Black]": {
      "editor.selectionBackground": "#add6ff50"
    }
  }`

**Comment by ViktorQvarfordt** [comment]
Thanks for pointing this out. If you send a PR I'd be happy to merge it.

@sharunkumar @mruf @jong82 @Salamanz18

**Comment by bhgsbatista** [comment]
This has been fixed and can be closed.
