### ISSUE TITLE
Hard to see highlighting of parameters/variables etc

### ISSUE THREAD

**Issue by Paxilein** [ViktorQvarfordt/vscode-pitch-black-theme#6]
![image](https://user-images.githubusercontent.com/24937322/101553922-803d6500-3a1a-11eb-80e1-5ed93c2c5cba.png)

As you can see here the color is maybe a bit too dark for those highlights and hard to see.

**Comment by ViktorQvarfordt** [comment]
Good point, I agree. Would you like to create a PR?

**Comment by Paxilein** [comment]
I tried to get the scope but have no idea what it is.... The normal scope-view doesn't show it...
It's in Json-files... My ps1-Powershell-Files look much better...
